### ISSUE TITLE
无法对接

### ISSUE THREAD

**Issue by ckaak** [Yuzuki616/V2bX#59]
**描述该错误**
无法对接，不知道是api node文件报错。

**复现**
启动，然后报错。

**环境和版本**
 - 系统 Debian 11
 - 架构 AMD64
 - 面板 V2board dev v1.7.4
 - 协议 vmess/ss
 - 版本  V2bX v1.1.7
 - 部署方式 一键脚本

**日志和错误**
 V2bX v1.1.7 (A V2board backend based on Xray-core)
 2023/05/13 21:21:48 Start V2bX...
 2023/05/13 21:21:48 Core Version: 1.8.0
 2023/05/13 21:21:48 [Warning] core: Xray 1.8.0 started
 panic: interface conversion: interface {} is float64, not string
 goroutine 1 [running]:
 github.com/Yuzuki616/V2bX/api/panel.(*Client).GetNodeInfo(0xc0010d6e00)
         github.com/Yuzuki616/V2bX/api/panel/node.go:80 +0x7b1
 github.com/Yuzuki616/V2bX/node/controller.(*Node).Start(0xc000f98b40)
         github.com/Yuzuki616/V2bX/node/controller/controller.go:45 +0xea
 github.com/Yuzuki616/V2bX/node.(*Node).Start(0xc000ff2de0, {0xc000994df8, 0x1, 0x419b71?}, 0xc000cadf90)
         github.com/Yuzuki616/V2bX/node/node.go:27 +0x188
 main.main()
         github.com/Yuzuki616/V2bX/main.go:51 +0x385
 V2bX.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
 V2bX.service: Failed with result 'exit-code'.

**额外的内容**

https://github.com/Yuzuki616/V2bX/blob/master/README.md
wget -N https://raw.githubusercontents.com/Yuzuki616/V2bX-script/master/install.sh && ash install.sh  这里差个b 

wget -N https://raw.githubusercontents.com/Yuzuki616/V2bX-script/master/install.sh  bash install.sh

https://crackair.gitbook.io/xrayr-project/ 文档私有了

**Comment by Yuzuki616** [comment]
已修复，麻烦等下个版本更新或者自己拿action里的替换

**Comment by ckaak** [comment]
> 已修复，麻烦等下个版本更新或者自己拿action里的替换

可以对接了。不过我发现打开VLESS，日志显示启动vmess，最后vless连不上。。。

**Comment by Yuzuki616** [comment]
配置文件有变动，自己看example

**Comment by ckaak** [comment]
> 配置文件有变动，自己看example

我看了历史变动，把EnableXTLS去掉了，EnableVless: true是打开的。日志报错： > proxy/vmess/encoding: invalid user > proxy/vmess: Not Found

**Comment by Yuzuki616** [comment]
EnableVless位置改了，现在的要写在ControllerConfig里

**Comment by ckaak** [comment]
> EnableVless位置改了，现在的要写在ControllerConfig里，之前的在ApiConfig

改好了可以运行，再问一下，现在删了流控代码吗？flow xtls-rprx-vision / xtls-rprx-direct 都不支持，只能同普通tls。

**Comment by Yuzuki616** [comment]
direct已经在上游被弃用，之后会去适配vision和reality

**Comment by TomorrowLost** [comment]
> direct已经在上游被弃用，之后会去适配vision和reality

软件安装脚本失效了
